zuul:
  routes:
    traking-api:
      sensitiveHeaders:
    earnings-api:
      sensitiveHeaders:
    details-api:
      sensitiveHeaders:
    
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 60000
  
eureka: 
  instance:
    prefer-ip-address: true